### ISSUE TITLE
User Login and Logout

### ISSUE THREAD

**Issue by freshkitedev** [freshkitedev/LMS-Project#5]
Generate a token for user login and logout.
https://youtu.be/hroIPiBr_5c?si=AXXUuiJWB-7bpYPn

**Comment by Vishva77** [comment]
loginUser: This function handles user authentication by validating the email and password provided in the request body, querying the database to find the user with the given email, comparing the password with the hashed password stored in the database, and sending a token if authentication is successful.

logoutUser: This function handles user logout by clearing the access_token and refresh_token cookies and sending a success message upon successful logout.


**commit id :** ba9a14fe038350be04c8724810f5bad1f92eafd7
