### ISSUE TITLE
Implement user authorization

### ISSUE THREAD

**Issue by freshkitedev** [freshkitedev/LMS-Project#7]
User Authorization || link: https://youtu.be/nAiGBtUpFO4?si=TudMk_bhufe0nuQE

**Comment by Vishva77** [comment]
Authentication Middleware (isAuthenticated):

Verifies if a user is authenticated by checking for an access token in the request cookies.
Decodes and verifies the access token using JWT.
Retrieves user data from Redis based on the token's decoded user ID.
Attaches the user data to the request object (req.user) if authenticated.

Authorization Middleware (authorizeRoles):

Validates if the authenticated user has required role(s) to access a resource.
Compares the user's role with specified roles and returns an error if access is forbidden.

Type Declaration for Express Request Object:

Extends the request object's type definition to include a user property of type IUser, representing the structure of a user model.
