### ISSUE TITLE
Order and Notification

### ISSUE THREAD

**Issue by freshkitedev** [freshkitedev/LMS-Project#9]
1. Create a model for notification and order.
2. Create order.
3. Get all notification and update notification status.
4. Delete notifications -- with crone after a certain time.

**Comment by shilpa053020** [comment]
I have not tested my code yet because still need to implement user authentication. Once the authentication process for the user is completed, I will proceed to test my code and address any potential issues.

**Comment by shilpa053020** [comment]
**1.Create a model for notification and order.**
       I have completed and raised PR but still not yet merged.
**2.Create order.**
            I have not tested my code yet because still need to implement user authentication. Once the authentication process for the user is completed, I will proceed to test my code and address any potential issues.

**Comment by shilpa053020** [comment]
**Get all notification and update notification status. 
Delete notifications -- with crone after a certain time.**
I have completed the Issue.
